version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./config/docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=students_db_user
      - POSGTGRES_PASSWORD=435363
      - POSTGRES_DB=students_db
    ports:
      - "5434:5432"